# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:bath-heater:0000A028:yeelink-v5:1

from enum import IntEnum

SRV_Device_Information = 1
PROP_Device_Manufacturer = 1
PROP_Device_Model = 2
PROP_Device_Serial_Number = 3
PROP_Current_Firmware_Version = 4

SRV_Light_Bath_Heater = 2
PROP_Switch_Status = 1 #bool #rwn
PROP_Mode = 2 #uint8 #w
class VALUE_Mode(IntEnum):
    Lighting = 1
    Night_Light = 2
PROP_Brightness = 3 #uint8 #rwn
class VALUE_Brightness(IntEnum):
    MIN = 1
    MAX = 100

SRV_PTC_Bath_Heater = 3
PROP_Mode = 1 #uint8 #rwn
class VALUE_Mode(IntEnum):
    Dry = 1
    Defog = 2
    Quick_Defog = 3
    Quick_Heat = 4
    Idle = 5
    None = 6
PROP_Heating = 2 #bool #rwn
PROP_Blow = 3 #bool #rwn
PROP_Ventilation = 4 #bool #rwn
PROP_Target_Temperature = 5 #uint8 #rwn
class VALUE_Target_Temperature(IntEnum):
    MIN = 25
    MAX = 45
PROP_Temperature = 6 #uint8
class VALUE_Temperature(IntEnum):
    MIN = 0
    MAX = 50
ACTION_Stop_Working = 1

ALL_PROPS = {1: {1: 'Device_Manufacturer', 2: 'Device_Model', 3: 'Device_Serial_Number', 4: 'Current_Firmware_Version'}, 2: {1: 'Switch_Status', 3: 'Brightness'}, 3: {1: 'Mode', 2: 'Heating', 3: 'Blow', 4: 'Ventilation', 5: 'Target_Temperature', 6: 'Temperature'}}

