# Generated by https://github.com/Yonsm/MiService

from enum import IntEnum

SRV_Device_Information = 1
PROP_Device_Manufacturer = 1
PROP_Device_Model = 2
PROP_Device_Serial_Number = 3
PROP_Current_Firmware_Version = 4

SRV_Fan = 2
PROP_Switch_Status = 1 #bool #rwn
PROP_Fan_Level = 2 #uint8 #rwn
class VALUE_Fan_Level(IntEnum):
    MIN = 1
    MAX = 4
PROP_Horizontal_Swing = 3 #bool #rwn
PROP_Horizontal_Angle = 4 #uint16 #rwn
class VALUE_Horizontal_Angle(IntEnum):
    MIN = 0
    MAX = 120
PROP_Mode = 5 #uint8 #rw
class VALUE_Mode(IntEnum):
    Straight_Wind = 0
    Natural_Wind = 1

SRV_Physical_Control_Locked = 3
PROP_Physical_Control_Locked = 1 #bool #rw

SRV_Alarm = 4
PROP_Alarm = 1 #bool #rwn

SRV_Indicator_Light = 5
PROP_Switch_Status = 1 #bool #rwn


