# Generated by https://github.com/Yonsm/MiService

from enum import IntEnum

SRV_Device_Information = 1
PROP_Device_Manufacturer = 1
PROP_Device_Model = 2
PROP_Device_Serial_Number = 3
PROP_Current_Firmware_Version = 4

SRV_Fan = 2
PROP_Switch_Status = 1 #bool #rwn
PROP_Gear_Fan_Level_ = 2 #uint8 #rwn
class VALUE_Gear_Fan_Level_(IntEnum):
    1 = 1
    2 = 2
    3 = 3
    4 = 4
    5 = 5
PROP_Horizontal_Swing = 3 #bool #rwn
PROP_Vertical_Swing = 4 #bool #rwn
PROP_Horizontal_Angle = 5 #uint16 #rwn
class VALUE_Horizontal_Angle(IntEnum):
    MIN = 0
    MAX = 120
PROP_Vertical_Angle = 6 #uint8 #rwn
class VALUE_Vertical_Angle(IntEnum):
    MIN = 0
    MAX = 90
PROP_Mode = 7 #uint8 #rwn
class VALUE_Mode(IntEnum):
    Natural_Wind = 0
    Straight_Wind = 1
PROP_Status = 8 #uint8 #rn
class VALUE_Status(IntEnum):
    Idle = 1
    Busy = 2
PROP_Device_Fault = 9 #uint8 #rn
class VALUE_Device_Fault(IntEnum):
    Nofaults = 0
    Stuck = 1
    2 = 2
PROP_Brightness = 10 #uint8 #rwn
class VALUE_Brightness(IntEnum):
    MIN = 0
    MAX = 1
PROP_Alarm = 11 #bool #rwn

SRV_Physical_Control_Locked = 6
PROP_Physical_Control_Locked = 1 #bool #rwn
PROP_Current_Physical_Control_Lock = 2 #bool #rn

SRV_ = 5
PROP_定时 = 2 #uint32 #rnw
class VALUE_定时(IntEnum):
    MIN = 0
    MAX = 8
PROP_左右回正开关 = 4 #bool #rwn
PROP_上下回正开关 = 5 #bool #rnw
PROP_设定风扇左右转动7.5度 = 6 #w
PROP_设定风扇水平转动7.5度 = 7 #w
PROP_one-key-cycle = 8 #bool #w
PROP_one-key-back = 9 #bool #w
PROP_stepless-fan-level = 10 #uint8 #rnw
class VALUE_stepless-fan-level(IntEnum):
    MIN = 1
    MAX = 100

SRV_custom-service = 7
PROP_toggle = 1 #bool #w
ACTION_toggle-switch = 1 #in=[1]
ACTION_toggle-mode = 2 #in=[1]
ACTION_toggle-level = 3 #in=[1]


